load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "errors.go",
        "tls.go",
    ],
    importpath = "github.com/cigarframework/reconciled/pkg/common",
    visibility = ["//visibility:public"],
)
